language: node_js

node_js:
  - 'lts/*'
on:
  push:
    branches:
      - '**'

stages:
  - name: ghosoun_build
  - name: e2e_tests

jobs:
  include:
    - stage: ghosoun_build
      name: Checkout
      uses: actions/checkout@v2

    - stage: "ghosouon_build"
      name: Log Git SHA
      run: echo "$GITHUB_SHA"

    - stage: "ghosoun_build"
      name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        run: npm ci

    - stage: e2e_tests
      name: Run Tests
      run: npm run cypress:ci

  batch-completion-notification:
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Update Applitools batch status
        uses: wei/curl@v1.1.1
        with:
          args: -d "" -X POST https://eyesapi.applitools.com/api/externals/github/servers/github.com/commit/$GITHUB_SHA/complete?apiKey=$APPLITOOLS_API_KEY
